### ISSUE TITLE
[Feature]: Test step details and association of the attachments with each step

### ISSUE THREAD

**Issue by aloysiusmartis** [alexneo2003/playwright-azure-reporter#4]
as part of the update of the test case in Azure DevOps, can we have the Test step details also copied in to test run as well as associated the attachments with each step(see attached screen grab)?
![Screen Shot 2022-09-24 at 4 49 18 PM](https://user-images.githubusercontent.com/2643339/192122627-813a57c0-2767-4791-a932-379b5c9d9aff.png)

**Comment by alexneo2003** [comment]
It's good idea.
I'm researching this question and as i seen playwright in his [steps](https://playwright.dev/docs/api/class-teststep) does not have step status. And, as example, inside pw html reporter failed step looks like it passed.

![image](https://user-images.githubusercontent.com/11705902/192135734-94f2f615-a24d-4ee0-b9c8-c1efd31ed5d6.png)

i'm closing issue because at this time it as this is currently not possible due to playwright restrictions

**Comment by joerg1985** [comment]
@alexneo2003 i think this might have changed, in my report the step is marked as failed.
I thinks the [TestStep.error](https://playwright.dev/docs/api/class-teststep#test-step-error) field could be the needed one.

![image](https://user-images.githubusercontent.com/16140691/217494187-5f8e3a71-1ed0-4698-b727-dc89c888c9ff.png)

This would be a great feature for this plugin.

**Comment by alexneo2003** [comment]
@joerg1985 can you create new feature for this? i'm should try to investigate this question much more detailed

**Comment by joerg1985** [comment]
i think the missing await is the reason why the status was not reflected in the example above.

`page.waitForNavigation(...` should be `await page.waitForNavigation(...` 



> It's good idea. I'm researching this question and as i seen playwright in his [steps](https://playwright.dev/docs/api/class-teststep) does not have step status. And, as example, inside pw html reporter failed step looks like it passed.
> 
> ![image](https://user-images.githubusercontent.com/11705902/192135734-94f2f615-a24d-4ee0-b9c8-c1efd31ed5d6.png)
> 
> i'm closing issue because at this time it as this is currently not possible due to playwright restrictions
